### ISSUE TITLE
[功能请求]支持导入enka原始角色数据或gsuid修改数据的json

### ISSUE THREAD

**Issue by KimigaiiWuyi** [never1andwxy/GenshinImpactDMGvisualizer_WEB#10]
[enka地址](https://enka.shinshin.moe/)
[enkaAPI返回原始数据Json示例](https://raw.githubusercontent.com/KimigaiiWuyi/GenshinUID/main/enkaToData/player/102451072/rawData.json)
[gsuid修改单个数据Json示例](https://raw.githubusercontent.com/KimigaiiWuyi/GenshinUID/main/enkaToData/player/102451072/%E5%85%AB%E9%87%8D%E7%A5%9E%E5%AD%90.json)

我认为支持导入原始数据的话能做更多的事情

**Comment by Kamihimmel** [comment]
在你提出前 已经做好了 加群获得测试版

**Comment by KimigaiiWuyi** [comment]
> 在你提出前 已经做好了 加群获得测试版

群号是在……readme好像没看到有群号（
