### ISSUE TITLE
[BUG] 圣遗物副属性固定数值类属性只能通过拖动ruler改变值

### ISSUE THREAD

**Issue by wtof1996** [never1andwxy/GenshinImpactDMGvisualizer_WEB#2]
## BUG描述
在调整圣遗物副属性固定数值类的属性（如小攻击）时，只能通过拖动ruler改变值，旁边上下的小箭头改变值是无效的，主界面上显示的仍然是之前ruler选取的值。
百分比类数值不存在此问题。

## 复现步骤
以下举一个小攻击的例子：
1. 选取圣遗物生之花，点开设置副属性
2. 在倒数第二个“攻击力”前打钩
3. 将ruler向右拖动至任意一个10以上的数值，如39
4. 点两下ruler旁边向下的箭头，调整至37
5. 随意点击设置面板之外的其他位置，关闭设置面板
6. 此时已经可以看到攻击力的数值仍然是39，而不是期望的37

**Comment by Kamihimmel** [comment]
感谢查虫。这个bug刚刚的最新的版本已经修复。请ctrl+F5
