### ISSUE TITLE
[功能请求] 圣遗物数值允许手动输入数值，而不是只能通过滑块和按钮调整

### ISSUE THREAD

**Issue by Tsuk1ko** [never1andwxy/GenshinImpactDMGvisualizer_WEB#4]
只能用滑块和按钮调实在是有点痛苦……本来直接输入2秒钟的事情需要拖半天滑块再点按钮微调

**Comment by Kamihimmel** [comment]
主要输入还得搞输入框 还有数值检测 而且目前的滑块其实效率也不低了 目前暂时没计划修改这个地方 不过这个issue我留这里了 其他人可以在这提供自己的想法

**Comment by Tsuk1ko** [comment]
嗯……也没必要太严格的检测吧，就限定为 0 至 理论最大值 就好了，也不用非常精确，毕竟这个就是给自己看的，输爆表了也没有任何意义

主要滑块拖数值的时候中间小数也是连续的任意值，而不是限定有限的可能值，所以我觉得这里还是手动输入比较符合使用场景

现在的情况就类似于电话号码、生日年月日这种要用滑条输入，不是很合理😂

**Comment by Kamihimmel** [comment]
电话号码那已经是八位数以上了 肯定输入合理。但是生日年月日那安卓苹果默认可都是滑条（滚轮）哦。而且目前移动端使用还是滑条效率高一点 自己的数字占最大值多少比例一划然后微调即可（其他原神计算器就是要填的太多了很多人懒得用） 当然pc端输入数字需求我懂 不过感觉目前不是刚需了（懒得用这个区域直接去手动调节写就行了）当然手动调节区域是可以改进一下

**Comment by Kamihimmel** [comment]
已经增加了uid导入功能 认为不再存在类似输入问题 所以结束这个issue
