### ISSUE TITLE
[功能请求] 导入导出数据支持额外选项面板

### ISSUE THREAD

**Issue by Tsuk1ko** [never1andwxy/GenshinImpactDMGvisualizer_WEB#5]
这些选项会很大程度上影响计算结果，且选项繁多，理应能被导入导出，还能方便复制配置多开页面进行微调比较

（如果敌人选项也能顺便支持导入导出就更好了）

**Comment by Kamihimmel** [comment]
目前版本还不稳定 选项如果支持导出会影响之后版本的开发 一旦制作导出功能之后修改就不能随便改了 否则数据有可能损坏 不过敌人选项的话可以加入之后更新中 等稳定了之后再选定其他选项

**Comment by Kamihimmel** [comment]
已经支持导入额外选项面板
