### ISSUE TITLE
小建议：建议注明可能出现的短暂白屏等情况

### ISSUE THREAD

**Issue by YujioNako** [never1andwxy/GenshinImpactDMGvisualizer_WEB#6]
因为这个网站的加载结构比较特殊（指有个2M+的js），所以加载时间也会相对较长，许多用户都有发现长时间白屏、字体在一定时间内乱码的情况。
建议在index内注明这种可能出现的情况，以避免用户误解为服务器脱机/网页错误。

**Comment by kyasuragi** [comment]
感谢提议，我们会进行探讨

**Comment by kyasuragi** [comment]
@ldcivan さん
针对您提到的问题，我们进行了调查，白屏时间过长的主要原因倒不是因为js加载时间太久，而是渲染插件在中国大陆以外的服务器上导致。若您是在中国大陆以外地区访问，应该不会发生加载时间太长的情况。

若您是在中国大陆访问，建议您使用以下为中国大陆用户准备的做了本地化处理的国内镜像服务器。

https://genshin.kchlu.com

另外我们的应用做了一个官网，内提供Windows及安卓版本app下载，欢迎您来访问。

中国大陆：
https://genshincalc.kchlu.com

海外用户：
https://genshincalc.yunlu18.net

**Comment by Kamihimmel** [comment]
已经优化了国内的打开体验
