### ISSUE TITLE
[BUG] “额外选项面板”下的“手动调节”，对计算结果不起作用

### ISSUE THREAD

**Issue by ziyueye** [never1andwxy/GenshinImpactDMGvisualizer_WEB#7]
bug描述
-----------
对“额外选项面板”下的“手动调节”进行任意数值调节，右侧伤害面板数值保持不变

测试步骤
-----------
1. 面板数据初始化，“手动调节”为0，右侧伤害面板，融化暴击132202.6，如下
![image](https://user-images.githubusercontent.com/51165503/156899318-2b1f5255-69be-42c8-b71d-05b4d3d3469f.png)
2. “手动调节”面板修改攻击力百分比加成为100%，右侧伤害面板，融化暴击132202.6（无提升），如下
![image](https://user-images.githubusercontent.com/51165503/156899541-8f296cf0-5d8a-4450-9666-fa7d77b3a878.png)
3. “手动调节”面板其他加成同样，右侧伤害面板数值保持不变

**Comment by Kamihimmel** [comment]
兄弟 你没有点击左边按钮激活。。 官网专门有一行加粗的写了使用方式

**Comment by ziyueye** [comment]
> 

原来如此，感谢你的提醒，旅行者
