### ISSUE TITLE
圣遗物预设方案保存和每个角色的圣遗物方案固定

### ISSUE THREAD

**Issue by lemonchan1** [never1andwxy/GenshinImpactDMGvisualizer_WEB#8]
两个建议，1是增加一个圣遗物方案仓库，可以做到圣遗物选择的顶端那里然后侧边栏弹出选择，这样子比导出txt方便一些。2是对每个角色的圣遗物方案能够分别记忆和一键重置，不然每次看不同角色都要重新调整圣遗物很不方便。谢谢！

**Comment by AgileDojo022** [comment]
考虑增加圣遗物预置选项等功能，不过近期不会实装
对于不同角色 建议多开几个窗口
