### ISSUE TITLE
甘雨计算伤害和实际伤害不符

### ISSUE THREAD

**Issue by EwainCai** [never1andwxy/GenshinImpactDMGvisualizer_WEB#9]
**甘雨**
```攻击2339/暴伤234 一命 阿莫斯一精 乐团4```
实际伤害 ```1.9+3.8```
计算伤害 ```2.2+4.2```

**Comment by Kamihimmel** [comment]
请附带面板链接 顺便请检查自己激活属性

**Comment by EwainCai** [comment]
https://genshincalc.kchlu.com/build.html?id=2411

**Comment by EwainCai** [comment]
点错了普攻等级, 普攻居然能选到15级
